// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX2TrdArECdko_f_eTyZ79sAfXumDJCHI',
    appId: '1:884953162823:web:69e8e8137fb3bc15edfd62',
    messagingSenderId: '884953162823',
    projectId: 'plant-management-69e55',
    authDomain: 'plant-management-69e55.firebaseapp.com',
    databaseURL: "https://plant-management-69e55-default-rtdb.firebaseio.com",
    storageBucket: 'plant-management-69e55.firebasestorage.app',
    measurementId: 'G-0G0XWK6LNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp8ioIQa0aabcRJStIj7yfgTx_ktOep38',
    appId: '1:884953162823:android:434d4ceda8ef2514edfd62',
    messagingSenderId: '884953162823',
    projectId: 'plant-management-69e55',
    databaseURL: "https://plant-management-69e55-default-rtdb.firebaseio.com",
    storageBucket: 'plant-management-69e55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR9WyX-1RhodZchtQoMkPBU6AXEYIBFXw',
    appId: '1:884953162823:ios:0737808ac3cca0d5edfd62',
    messagingSenderId: '884953162823',
    projectId: 'plant-management-69e55',
    databaseURL: "https://plant-management-69e55-default-rtdb.firebaseio.com",
    storageBucket: 'plant-management-69e55.firebasestorage.app',
    iosBundleId: 'com.example.plantManagement',
  );
}
